name: dataforest
description: "Presidential Hackathon Taiwan - DataForest Environmental App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.7
  page_transition: ^2.0.9
  cupertino_icons: ^1.0.2
  flutter_map: ^5.0.0
  latlong2: ^0.9.1
  url_launcher: ^6.1.11
  geolocator: ^10.0.0
  http: ^1.1.0
  animations: ^2.0.11
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/backgrounds/intro_page.jpg
    - assets/images/backgrounds/login_page.jpg