name: dataforest
description: "Presidential Hackathon Taiwan - DataForest Environmental App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core navigation
  google_nav_bar: ^5.0.7
  page_transition: ^2.0.9
  cupertino_icons: ^1.0.2

  # Map packages (updated compatible versions)
  flutter_map: ^5.0.0
  flutter_map_heatmap: ^2.0.0
  latlong2: ^0.9.1
  url_launcher: ^6.1.11
  geolocator: ^10.0.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/